### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by KommareddyMonicaTejaswi** [INFO523-S24/project-final-MiningMinds#6]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

-[@h-akston] Maksim Kulik
-[@remisublette] Remi Hendershott
-[@suryavardhandama] Surya Vardhan Dama
-[@Sailaasya-1] Gorantla Sai Laasya
-[@KommareddyMonicaTejaswi] Monica Tejaswi Kommareddy
-[@xinformatics] Shashank Yadav
-[@Priom1996] Priom Mahmud
- ...

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, the research question well designed and is the data being used relevant to the research question. The use of whole dataset and other datset and comparision really shows the effort they put into the project. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, they did use good visualizations and the interpretation is accurate.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes, the project is really thought out. They did overcome the limitations within their dataset which is good. yes, it seems time and effort went into planning and implementation of the project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

yes the slides are decent and simple.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
- yes the team presented good, no body read off the slides but the team members could have been louder and more clear with the result interpretations.

**Comment by NandhiniAnne** [comment]
Thanks for your feedback!
