### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by gabegef** [INFO523-S24/project-final-MiningMinds#7]
The following is the peer review of the Presentation proposal by Analytical Avengers. The team members that participated in this review are 

- Sunday Usman - @sundayusman
- Tanya Evita George - @tanyageorge
- Mellika Akbarsharifi - @mellica97
- Divya Liladhar Dhole - @Divyadhole
- Mohammad Ali Farmani - @mfarmani95
- H M Abdul Fattah - @hmfattah
- Gabriel Gedaliah Geffen - @gabegef

- Content: Is the research question well designed and is the data being used relevant to the research question?

The research question is very high-level and well-defined, and the dataset they used seems to provide enough rows for the analysis. However, I believe that they don't have access to the raw data because a lot of this is private information, so there is a question as to how accurate the model results truly are.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

They provided the same ROC/AUC metrics that we provided for our classification model and confusion matrix. They interpreted them well, but could have discussed the possibility of overfitting a little bit more as there results are near perfect. Also, their F1 score is really low despite the high accuracy and precision.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

They did a great job and obviously put in a lot of time an effort, especially to manage a dataset as large as they did. The project is somewhat creative, but fraud detection is a topic that is already widely studied. As mentioned, one possible limitation is that all of the data is given as principal components, which may cause some error in the actual modeling.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides are well organized, and there are a lot of figures. However, some slides, like the question plan and introduction could have been designed to be a bit more enticing. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

They were very professional, and seemed like they put some effort into practicing their sections.

**Comment by NandhiniAnne** [comment]
Thanks for your feedback!!!!
